### ISSUE TITLE
crop area not moving in chrome, working fine in mozilla

### ISSUE THREAD

**Issue by arunsrivastavapulp** [fengyuanchen/cropper#831]
Hi All,

I am opening cropper in modal box. Cropper is working fine with mozilla but if i use it in chrome, crop area is not movable. Below is my code

$('#cropper-example-2-modal').on('shown.bs.modal', function () {
					$image.cropper({
						aspectRatio: aspect,
						data: {
							width: canvasW,
							height: canvasH
						},
						strict: true,
						highlight: false,
						viewMode: 1
					});
				});

**Comment by NettMore** [comment]
Hi.
I'm seeing this too. Works fine in firecox, but not ie and chrome.

**Comment by fengyuanchen** [comment]
Fixed this in the latest version (v3.0.0-alpha).

**Comment by NettMore** [comment]
I am still seeing this problem in Cropper v3.0.0-alpha.1

The getPointer function is not setting pageX and pageY because Chrome does not seem to pass these values in a jquery event object.

Line 1097 in Cropper.js

```javascript
function getPointer(_ref, endOnly) {
  var pageX = _ref.pageX,
      pageY = _ref.pageY;

// The next 2 lines get the pageX/Y from the oroginal event if it's not been defined 
// already and it works for me in Chrome now.
  if (!pageX) pageX = _ref.originalEvent.pageX;
  if (!pageY) pageY = _ref.originalEvent.pageY;

  var end = {
    endX: pageX,
    endY: pageY
  };
....
```

(Sorry ,don't know how to do a pull request properly!)

Hope that this helps. 

regards

Lawrence

**Comment by fengyuanchen** [comment]
What's the version of your Chrome?

**Comment by NettMore** [comment]
Hi.
Thanks for looking. I'm not on any specific version of Chrome, I guess it's the latest stable. I think I looked again and you may have fixed this with Cropper v3.0.0-alpha.1a as there was some changes in this area.
I've not managed to test as the project has moved on.
Regards

**Comment by Sariig** [comment]
I'm using v3.0.0-beta and am running into this issue. I'm using Version 59.0.3041.0 (Official Build) canary (64-bit) for Chrome Canary.

From what I can tell the issue is on line 1214:
pointers[originalEvent && originalEvent.pointerId || 0] = getPointer(e);

e is the event object which does not have properties for pageX or pageY in Chrome. I think it needs to use e.OriginalEvent.pageX and e.OriginalEvent.pageY instead.

**Comment by fengyuanchen** [comment]
@Sariig You can change the source code and check if it is the core problem.

**Comment by miravukojevic** [comment]
drag and drop not working on Mozilla.
Any idea? Thanks.
